name: pixelfield_flutter_task
description: "Test task for Pixelfield Flutter project"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  # Environment & Configuration
  flutter_dotenv: ^5.2.1

  # Dependency Injection
  get_it: ^8.0.3

  # State Management
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7

  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Routing
  go_router: ^14.7.1

  # Network & Connectivity
  connectivity_plus: ^6.1.2

  # Localization
  flutter_translate: ^4.1.0

  # UI & Styling
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7
  auto_size_text: ^3.0.0
  flutter_native_splash: ^2.4.4


  # Media
  youtube_player_flutter: ^9.1.1


dev_dependencies:
  build_runner: ^2.4.14
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


# For applying changes run   flutter clean && flutter pub get && flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#0B1519"
  image: assets/images/ic_logo.png
  branding: assets/images/ic_logo.png
  color_dark: "#0B1519"
  image_dark: assets/images/ic_logo.png
  branding_dark: assets/images/ic_logo.png

  android_12:
    image: assets/images/ic_logo.png
    icon_background_color: "#0B1519"
    image_dark: assets/images/ic_logo.png
    icon_background_color_dark: "#0B1519"

  web: false


flutter:
  assets:
    - .env

    - assets/images/img_bottle.png
    - assets/images/ic_collection.svg
    - assets/images/ic_scan.svg
    - assets/images/ic_settings.svg
    - assets/images/ic_shop.svg
    - assets/images/ic_bell.svg
    - assets/images/ic_badge.svg
    - assets/images/ic_down.svg
    - assets/images/img_bottle_background.png
    - assets/images/img_genuine.png
    - assets/images/ic_clip.svg
    - assets/images/ic_logo.png

    - assets/i18n/
    - assets/data/

  uses-material-design: true


